name: Build App
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds, Windows is unsupported
        options:
          - ubuntu-latest
          - macos-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
          - previewMain

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: npm
          
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          
      - name: Install dependencies
        run: npm install
        
      - name: Install expo-dev-client for development builds
        if: github.event.inputs.profile == 'development'
        run: npx expo install expo-dev-client
        
      - name: Debug token and verify EAS authentication
        run: |
          echo "Debugging token setup..."
          if [ -n "$EXPO_TOKEN" ]; then
            echo "✓ EXPO_TOKEN is set (length: ${#EXPO_TOKEN})"
            echo "✓ Token starts with: ${EXPO_TOKEN:0:10}..."
          else
            echo "✗ EXPO_TOKEN is not set or empty"
            echo "Available environment variables:"
            env | grep -i expo || echo "No EXPO variables found"
            exit 1
          fi
          
          echo "Checking EAS authentication..."
          eas whoami
          
      - name: Build app with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --local \
            --non-interactive \
            --platform=${{ github.event.inputs.platform }} \
            --profile=${{ github.event.inputs.profile }}
            
      - name: List build directory contents
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Searching for build artifacts..."
          find . -type f \( -iname "*.apk" -o -iname "*.aab" -o -iname "*.ipa" \) -exec ls -la {} \;
          
      - name: Locate built file
        id: find-artifact
        run: |
          ARTIFACT_PATH=$(find . -type f \( -iname "*.apk" -o -iname "*.aab" -o -iname "*.ipa" \) | head -n 1)
          if [ -z "$ARTIFACT_PATH" ]; then
            echo "No build artifact found!"
            exit 1
          fi
          echo "Found artifact: $ARTIFACT_PATH"
          echo "artifact-path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT
          
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.platform }}-${{ github.event.inputs.profile }}
          path: ${{ steps.find-artifact.outputs.artifact-path }}
